### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by zestfulapple** [azirbel/photo-tools#1]
1. make the "Date Modified" and "Date Created" their actual, correct dates
2. auto-create the "output" folder
3. user can choose to create month folders or not
4. write in documentation an example of what Joyce should run in the terminal

**Comment by azirbel** [comment]
Added features in https://github.com/azirbel/photo-tools/commit/b07119c80b7c19d5968a9e749261ade3d6e0acc0. See the new README at https://github.com/azirbel/photo-tools for instructions.
